type Row = { method: string; complexity: string; notes: string };
export type LangData = Record<string, Row[]>;

// -- C++
const CPP_TIME_COMPL: LangData = {
  vector: [
    { method: "push_back()", complexity: "O(1)", notes: "Amortized" },
    { method: "pop_back()", complexity: "O(1)", notes: "" },
    { method: "insert()", complexity: "O(n)", notes: "Shifts elements" },
    { method: "erase()", complexity: "O(n)", notes: "Shifts elements" },
    { method: "at()", complexity: "O(1)", notes: "" },
    { method: "operator[]", complexity: "O(1)", notes: "" },
    { method: "size()", complexity: "O(1)", notes: "" },
    { method: "find()", complexity: "O(n)", notes: "Linear scan" },
    { method: "sort()", complexity: "O(n log n)", notes: "Introsort" },
    { method: "reverse()", complexity: "O(n)", notes: "" },
    { method: "clear()", complexity: "O(n)", notes: "Destroys elements" },
  ],
  map: [
    { method: "insert()", complexity: "O(log n)", notes: "Red-black tree" },
    { method: "find()", complexity: "O(log n)", notes: "" },
    { method: "erase()", complexity: "O(log n)", notes: "" },
    {
      method: "operator[]",
      complexity: "O(log n)",
      notes: "Inserts if missing",
    },
    { method: "count()", complexity: "O(log n)", notes: "" },
    { method: "size()", complexity: "O(1)", notes: "" },
    { method: "clear()", complexity: "O(n)", notes: "" },
  ],
  unordered_map: [
    { method: "insert()", complexity: "O(1)", notes: "Amortized" },
    { method: "find()", complexity: "O(1)", notes: "Amortized" },
    { method: "erase()", complexity: "O(1)", notes: "Amortized" },
    { method: "operator[]", complexity: "O(1)", notes: "Amortized" },
    { method: "count()", complexity: "O(1)", notes: "Amortized" },
    { method: "size()", complexity: "O(1)", notes: "" },
    { method: "clear()", complexity: "O(n)", notes: "" },
  ],
  set: [
    { method: "insert()", complexity: "O(log n)", notes: "Red-black tree" },
    { method: "find()", complexity: "O(log n)", notes: "" },
    { method: "erase()", complexity: "O(log n)", notes: "" },
    { method: "count()", complexity: "O(log n)", notes: "" },
    { method: "size()", complexity: "O(1)", notes: "" },
    { method: "clear()", complexity: "O(n)", notes: "" },
  ],
  unordered_set: [
    { method: "insert()", complexity: "O(1)", notes: "Amortized" },
    { method: "find()", complexity: "O(1)", notes: "Amortized" },
    { method: "erase()", complexity: "O(1)", notes: "Amortized" },
    { method: "count()", complexity: "O(1)", notes: "Amortized" },
    { method: "size()", complexity: "O(1)", notes: "" },
    { method: "clear()", complexity: "O(n)", notes: "" },
  ],
  deque: [
    { method: "push_front()", complexity: "O(1)", notes: "" },
    { method: "push_back()", complexity: "O(1)", notes: "" },
    { method: "pop_front()", complexity: "O(1)", notes: "" },
    { method: "pop_back()", complexity: "O(1)", notes: "" },
    { method: "operator[]", complexity: "O(1)", notes: "" },
    { method: "insert()", complexity: "O(n)", notes: "" },
    { method: "erase()", complexity: "O(n)", notes: "" },
  ],
  string: [
    { method: "push_back()", complexity: "O(1)", notes: "Amortized" },
    { method: "append()", complexity: "O(n)", notes: "" },
    { method: "find()", complexity: "O(n)", notes: "" },
    { method: "substr()", complexity: "O(n)", notes: "" },
    { method: "replace()", complexity: "O(n)", notes: "" },
    { method: "size()", complexity: "O(1)", notes: "" },
    { method: "operator[]", complexity: "O(1)", notes: "" },
    { method: "compare()", complexity: "O(n)", notes: "" },
  ],
};

// -- Rust
const RUST_TIME_COMPL: LangData = {
  vec: [
    { method: "push()", complexity: "O(1)", notes: "Amortized" },
    { method: "pop()", complexity: "O(1)", notes: "" },
    { method: "insert()", complexity: "O(n)", notes: "Shifts elements" },
    { method: "remove()", complexity: "O(n)", notes: "Shifts elements" },
    { method: "get()", complexity: "O(1)", notes: "" },
    { method: "len()", complexity: "O(1)", notes: "" },
    { method: "contains()", complexity: "O(n)", notes: "" },
    { method: "iter()", complexity: "O(1)", notes: "Iterator creation" },
    { method: "sort()", complexity: "O(n log n)", notes: "Timsort" },
    { method: "dedup()", complexity: "O(n)", notes: "Must be sorted first" },
    { method: "retain()", complexity: "O(n)", notes: "" },
    { method: "clear()", complexity: "O(n)", notes: "Drops elements" },
  ],
  hashmap: [
    { method: "insert()", complexity: "O(1)", notes: "Amortized" },
    { method: "get()", complexity: "O(1)", notes: "Amortized" },
    { method: "remove()", complexity: "O(1)", notes: "Amortized" },
    { method: "contains_key()", complexity: "O(1)", notes: "Amortized" },
    { method: "len()", complexity: "O(1)", notes: "" },
    { method: "iter()", complexity: "O(1)", notes: "Iterator creation" },
    { method: "entry()", complexity: "O(1)", notes: "Amortized" },
  ],
  hashset: [
    { method: "insert()", complexity: "O(1)", notes: "Amortized" },
    { method: "contains()", complexity: "O(1)", notes: "Amortized" },
    { method: "remove()", complexity: "O(1)", notes: "Amortized" },
    { method: "len()", complexity: "O(1)", notes: "" },
    { method: "union()", complexity: "O(n)", notes: "" },
    { method: "intersection()", complexity: "O(n)", notes: "" },
  ],
  btreemap: [
    { method: "insert()", complexity: "O(log n)", notes: "B-tree" },
    { method: "get()", complexity: "O(log n)", notes: "" },
    { method: "remove()", complexity: "O(log n)", notes: "" },
    { method: "contains_key()", complexity: "O(log n)", notes: "" },
    { method: "len()", complexity: "O(1)", notes: "" },
  ],
  string: [
    { method: "push_str()", complexity: "O(n)", notes: "" },
    { method: "push()", complexity: "O(1)", notes: "Amortized" },
    { method: "contains()", complexity: "O(n)", notes: "" },
    { method: "find()", complexity: "O(n)", notes: "" },
    { method: "replace()", complexity: "O(n)", notes: "" },
    { method: "split()", complexity: "O(n)", notes: "" },
    { method: "len()", complexity: "O(1)", notes: "" },
    { method: "chars()", complexity: "O(1)", notes: "Iterator creation" },
  ],
};

// -- Node.js
const NODEJS_TIME_COMPL: LangData = {
  array: [
    { method: "push()", complexity: "O(1)", notes: "Amortized" },
    { method: "pop()", complexity: "O(1)", notes: "" },
    { method: "shift()", complexity: "O(n)", notes: "Re-indexes all" },
    { method: "unshift()", complexity: "O(n)", notes: "Re-indexes all" },
    { method: "indexOf()", complexity: "O(n)", notes: "Linear scan" },
    { method: "includes()", complexity: "O(n)", notes: "" },
    { method: "find()", complexity: "O(n)", notes: "" },
    { method: "filter()", complexity: "O(n)", notes: "" },
    { method: "map()", complexity: "O(n)", notes: "" },
    { method: "reduce()", complexity: "O(n)", notes: "" },
    { method: "sort()", complexity: "O(n log n)", notes: "TimSort" },
    { method: "splice()", complexity: "O(n)", notes: "" },
    { method: "slice()", complexity: "O(n)", notes: "" },
    { method: "flat()", complexity: "O(n)", notes: "Depth dependent" },
    { method: "forEach()", complexity: "O(n)", notes: "" },
  ],
  map: [
    { method: "set()", complexity: "O(1)", notes: "" },
    { method: "get()", complexity: "O(1)", notes: "" },
    { method: "has()", complexity: "O(1)", notes: "" },
    { method: "delete()", complexity: "O(1)", notes: "" },
    { method: "clear()", complexity: "O(n)", notes: "" },
    { method: "forEach()", complexity: "O(n)", notes: "" },
    { method: "size", complexity: "O(1)", notes: "Cached property" },
  ],
  set: [
    { method: "add()", complexity: "O(1)", notes: "" },
    { method: "has()", complexity: "O(1)", notes: "" },
    { method: "delete()", complexity: "O(1)", notes: "" },
    { method: "clear()", complexity: "O(n)", notes: "" },
    { method: "forEach()", complexity: "O(n)", notes: "" },
    { method: "size", complexity: "O(1)", notes: "Cached property" },
  ],
  object: [
    { method: "obj[key]", complexity: "O(1)", notes: "Hash lookup" },
    { method: "delete obj[key]", complexity: "O(1)", notes: "" },
    { method: "Object.keys()", complexity: "O(n)", notes: "" },
    { method: "Object.values()", complexity: "O(n)", notes: "" },
    { method: "Object.entries()", complexity: "O(n)", notes: "" },
    { method: "Object.assign()", complexity: "O(n)", notes: "" },
    { method: "{...spread}", complexity: "O(n)", notes: "Shallow copy" },
  ],
  buffer: [
    { method: "Buffer.alloc()", complexity: "O(n)", notes: "Zero-fills" },
    { method: "Buffer.from()", complexity: "O(n)", notes: "" },
    { method: "buf.copy()", complexity: "O(n)", notes: "" },
    { method: "buf.slice()", complexity: "O(1)", notes: "View, no copy" },
    { method: "buf.indexOf()", complexity: "O(n)", notes: "" },
    { method: "buf.includes()", complexity: "O(n)", notes: "" },
    { method: "buf.toString()", complexity: "O(n)", notes: "" },
  ],
  string: [
    { method: "charAt()", complexity: "O(1)", notes: "" },
    { method: "charCodeAt()", complexity: "O(1)", notes: "" },
    { method: "at()", complexity: "O(1)", notes: "" },
    { method: "indexOf()", complexity: "O(n)", notes: "" },
    { method: "includes()", complexity: "O(n)", notes: "" },
    { method: "startsWith()", complexity: "O(n)", notes: "" },
    { method: "endsWith()", complexity: "O(n)", notes: "" },
    { method: "slice()", complexity: "O(n)", notes: "Copy" },
    { method: "split()", complexity: "O(n)", notes: "" },
    { method: "replace()", complexity: "O(n)", notes: "" },
    { method: "replaceAll()", complexity: "O(n)", notes: "" },
    { method: "trim()", complexity: "O(n)", notes: "" },
    { method: "toLowerCase()", complexity: "O(n)", notes: "" },
    { method: "toUpperCase()", complexity: "O(n)", notes: "" },
    { method: "repeat()", complexity: "O(n)", notes: "n = result length" },
    { method: "padStart()", complexity: "O(n)", notes: "" },
    { method: "padEnd()", complexity: "O(n)", notes: "" },
    { method: "match()", complexity: "O(n)", notes: "Regex dependent" },
    { method: "concat()", complexity: "O(n)", notes: "" },
  ],
  math: [
    { method: "Math.floor()", complexity: "O(1)", notes: "" },
    { method: "Math.ceil()", complexity: "O(1)", notes: "" },
    { method: "Math.round()", complexity: "O(1)", notes: "" },
    { method: "Math.abs()", complexity: "O(1)", notes: "" },
    { method: "Math.pow()", complexity: "O(1)", notes: "" },
    { method: "Math.sqrt()", complexity: "O(1)", notes: "" },
    { method: "Math.random()", complexity: "O(1)", notes: "" },
    { method: "Math.max()", complexity: "O(n)", notes: "n = args count" },
    { method: "Math.min()", complexity: "O(n)", notes: "n = args count" },
    { method: "parseInt()", complexity: "O(n)", notes: "n = string length" },
    { method: "parseFloat()", complexity: "O(n)", notes: "n = string length" },
    { method: "Number.isInteger()", complexity: "O(1)", notes: "" },
    { method: "Number.isNaN()", complexity: "O(1)", notes: "" },
    { method: "Number.isFinite()", complexity: "O(1)", notes: "" },
  ],
  json: [
    { method: "JSON.parse()", complexity: "O(n)", notes: "n = string length" },
    {
      method: "JSON.stringify()",
      complexity: "O(n)",
      notes: "n = object size",
    },
  ],
  promise: [
    { method: "Promise.resolve()", complexity: "O(1)", notes: "" },
    { method: "Promise.reject()", complexity: "O(1)", notes: "" },
    { method: "Promise.all()", complexity: "O(n)", notes: "Waits for all" },
    { method: "Promise.allSettled()", complexity: "O(n)", notes: "" },
    { method: "Promise.race()", complexity: "O(n)", notes: "First to settle" },
    { method: "Promise.any()", complexity: "O(n)", notes: "First to fulfill" },
  ],
};

// -- Python
const PYTHON_TIME_COMPL: LangData = {
  list: [
    { method: "append()", complexity: "O(1)", notes: "Amortized" },
    { method: "pop()", complexity: "O(1)", notes: "From end" },
    { method: "pop(i)", complexity: "O(n)", notes: "From index" },
    { method: "insert()", complexity: "O(n)", notes: "" },
    { method: "remove()", complexity: "O(n)", notes: "" },
    { method: "index()", complexity: "O(n)", notes: "" },
    { method: "count()", complexity: "O(n)", notes: "" },
    { method: "sort()", complexity: "O(n log n)", notes: "Timsort" },
    { method: "reverse()", complexity: "O(n)", notes: "" },
    { method: "copy()", complexity: "O(n)", notes: "Shallow" },
    { method: "extend()", complexity: "O(n)", notes: "" },
    { method: "clear()", complexity: "O(n)", notes: "" },
    { method: "list[i]", complexity: "O(1)", notes: "" },
    { method: "len()", complexity: "O(1)", notes: "" },
  ],
  dict: [
    { method: "dict[key]", complexity: "O(1)", notes: "Amortized" },
    { method: "dict[key] = v", complexity: "O(1)", notes: "Amortized" },
    { method: "del dict[key]", complexity: "O(1)", notes: "Amortized" },
    { method: "key in dict", complexity: "O(1)", notes: "Amortized" },
    { method: "get()", complexity: "O(1)", notes: "" },
    { method: "keys()", complexity: "O(1)", notes: "View object" },
    { method: "values()", complexity: "O(1)", notes: "View object" },
    { method: "items()", complexity: "O(1)", notes: "View object" },
    { method: "update()", complexity: "O(n)", notes: "" },
    { method: "pop()", complexity: "O(1)", notes: "" },
    { method: "clear()", complexity: "O(n)", notes: "" },
    { method: "len()", complexity: "O(1)", notes: "" },
  ],
  set: [
    { method: "add()", complexity: "O(1)", notes: "Amortized" },
    { method: "remove()", complexity: "O(1)", notes: "Amortized" },
    { method: "discard()", complexity: "O(1)", notes: "No error if missing" },
    { method: "in operator", complexity: "O(1)", notes: "Amortized" },
    { method: "union()", complexity: "O(n)", notes: "" },
    { method: "intersection()", complexity: "O(n)", notes: "" },
    { method: "difference()", complexity: "O(n)", notes: "" },
    { method: "issubset()", complexity: "O(n)", notes: "" },
    { method: "len()", complexity: "O(1)", notes: "" },
    { method: "clear()", complexity: "O(n)", notes: "" },
  ],
  deque: [
    { method: "appendleft()", complexity: "O(1)", notes: "" },
    { method: "append()", complexity: "O(1)", notes: "" },
    { method: "popleft()", complexity: "O(1)", notes: "" },
    { method: "pop()", complexity: "O(1)", notes: "" },
    { method: "rotate()", complexity: "O(n)", notes: "" },
    { method: "index()", complexity: "O(n)", notes: "" },
    { method: "len()", complexity: "O(1)", notes: "" },
  ],
  string: [
    { method: "str[i]", complexity: "O(1)", notes: "" },
    { method: "len()", complexity: "O(1)", notes: "" },
    { method: "find()", complexity: "O(n)", notes: "" },
    { method: "replace()", complexity: "O(n)", notes: "" },
    { method: "split()", complexity: "O(n)", notes: "" },
    { method: "join()", complexity: "O(n)", notes: "" },
    { method: "strip()", complexity: "O(n)", notes: "" },
    { method: "lower()", complexity: "O(n)", notes: "" },
    { method: "upper()", complexity: "O(n)", notes: "" },
    { method: "count()", complexity: "O(n)", notes: "" },
    { method: "startswith()", complexity: "O(n)", notes: "" },
    { method: "endswith()", complexity: "O(n)", notes: "" },
  ],
};

// -- C
const C_TIME_COMPL: LangData = {
  array: [
    { method: "arr[i]", complexity: "O(1)", notes: "Direct access" },
    { method: "arr[i] = v", complexity: "O(1)", notes: "" },
    { method: "memcpy()", complexity: "O(n)", notes: "" },
    { method: "memmove()", complexity: "O(n)", notes: "" },
    { method: "memset()", complexity: "O(n)", notes: "" },
    { method: "memcmp()", complexity: "O(n)", notes: "" },
    { method: "qsort()", complexity: "O(n log n)", notes: "Usually quicksort" },
    { method: "bsearch()", complexity: "O(log n)", notes: "Must be sorted" },
    { method: "strlen()", complexity: "O(n)", notes: "" },
    { method: "strcpy()", complexity: "O(n)", notes: "" },
    { method: "strcmp()", complexity: "O(n)", notes: "" },
    { method: "strcat()", complexity: "O(n)", notes: "" },
    { method: "strchr()", complexity: "O(n)", notes: "" },
    { method: "strstr()", complexity: "O(n*m)", notes: "Naive search" },
  ],
  memory: [
    { method: "malloc()", complexity: "O(1)", notes: "Amortized" },
    { method: "calloc()", complexity: "O(n)", notes: "Zero-fills" },
    { method: "realloc()", complexity: "O(n)", notes: "May copy" },
    { method: "free()", complexity: "O(1)", notes: "" },
  ],
};

// -- Java
const JAVA_TIME_COMPL: LangData = {
  arraylist: [
    { method: "add()", complexity: "O(1)", notes: "Amortized" },
    { method: "add(i, e)", complexity: "O(n)", notes: "Shifts elements" },
    { method: "remove(i)", complexity: "O(n)", notes: "Shifts elements" },
    { method: "get(i)", complexity: "O(1)", notes: "" },
    { method: "set(i, e)", complexity: "O(1)", notes: "" },
    { method: "indexOf()", complexity: "O(n)", notes: "" },
    { method: "contains()", complexity: "O(n)", notes: "" },
    { method: "size()", complexity: "O(1)", notes: "" },
    { method: "clear()", complexity: "O(n)", notes: "" },
    { method: "sort()", complexity: "O(n log n)", notes: "TimSort" },
  ],
  hashmap: [
    { method: "put()", complexity: "O(1)", notes: "Amortized" },
    { method: "get()", complexity: "O(1)", notes: "Amortized" },
    { method: "remove()", complexity: "O(1)", notes: "Amortized" },
    { method: "containsKey()", complexity: "O(1)", notes: "Amortized" },
    { method: "containsValue()", complexity: "O(n)", notes: "" },
    { method: "keySet()", complexity: "O(1)", notes: "" },
    { method: "values()", complexity: "O(1)", notes: "" },
    { method: "size()", complexity: "O(1)", notes: "" },
    { method: "clear()", complexity: "O(n)", notes: "" },
  ],
  treemap: [
    { method: "put()", complexity: "O(log n)", notes: "Red-black tree" },
    { method: "get()", complexity: "O(log n)", notes: "" },
    { method: "remove()", complexity: "O(log n)", notes: "" },
    { method: "containsKey()", complexity: "O(log n)", notes: "" },
    { method: "firstKey()", complexity: "O(log n)", notes: "" },
    { method: "lastKey()", complexity: "O(log n)", notes: "" },
    { method: "size()", complexity: "O(1)", notes: "" },
  ],
  hashset: [
    { method: "add()", complexity: "O(1)", notes: "Amortized" },
    { method: "contains()", complexity: "O(1)", notes: "Amortized" },
    { method: "remove()", complexity: "O(1)", notes: "Amortized" },
    { method: "size()", complexity: "O(1)", notes: "" },
    { method: "clear()", complexity: "O(n)", notes: "" },
  ],
  linkedlist: [
    { method: "addFirst()", complexity: "O(1)", notes: "" },
    { method: "addLast()", complexity: "O(1)", notes: "" },
    { method: "removeFirst()", complexity: "O(1)", notes: "" },
    { method: "removeLast()", complexity: "O(1)", notes: "" },
    { method: "get(i)", complexity: "O(n)", notes: "No random access" },
    { method: "contains()", complexity: "O(n)", notes: "" },
    { method: "size()", complexity: "O(1)", notes: "" },
  ],
  string: [
    { method: "charAt()", complexity: "O(1)", notes: "" },
    { method: "indexOf()", complexity: "O(n)", notes: "" },
    { method: "substring()", complexity: "O(n)", notes: "" },
    { method: "contains()", complexity: "O(n)", notes: "" },
    { method: "replace()", complexity: "O(n)", notes: "" },
    { method: "split()", complexity: "O(n)", notes: "" },
    { method: "toLowerCase()", complexity: "O(n)", notes: "" },
    { method: "trim()", complexity: "O(n)", notes: "" },
    { method: "length()", complexity: "O(1)", notes: "" },
    { method: "equals()", complexity: "O(n)", notes: "" },
    { method: "compareTo()", complexity: "O(n)", notes: "" },
  ],
};

// -- C#
const CSHARP_TIME_COMPL: LangData = {
  list: [
    { method: "Add()", complexity: "O(1)", notes: "Amortized" },
    { method: "Insert()", complexity: "O(n)", notes: "Shifts elements" },
    { method: "Remove()", complexity: "O(n)", notes: "" },
    { method: "RemoveAt()", complexity: "O(n)", notes: "" },
    { method: "Contains()", complexity: "O(n)", notes: "" },
    { method: "IndexOf()", complexity: "O(n)", notes: "" },
    { method: "Sort()", complexity: "O(n log n)", notes: "Introsort" },
    { method: "Find()", complexity: "O(n)", notes: "" },
    { method: "Count", complexity: "O(1)", notes: "Property" },
    { method: "Clear()", complexity: "O(n)", notes: "" },
    { method: "list[i]", complexity: "O(1)", notes: "" },
  ],
  dictionary: [
    { method: "Add()", complexity: "O(1)", notes: "Amortized" },
    { method: "dict[key]", complexity: "O(1)", notes: "Amortized" },
    { method: "Remove()", complexity: "O(1)", notes: "Amortized" },
    { method: "ContainsKey()", complexity: "O(1)", notes: "Amortized" },
    { method: "ContainsValue()", complexity: "O(n)", notes: "" },
    { method: "TryGetValue()", complexity: "O(1)", notes: "" },
    { method: "Keys", complexity: "O(1)", notes: "Property" },
    { method: "Values", complexity: "O(1)", notes: "Property" },
    { method: "Count", complexity: "O(1)", notes: "Property" },
    { method: "Clear()", complexity: "O(n)", notes: "" },
  ],
  hashset: [
    { method: "Add()", complexity: "O(1)", notes: "Amortized" },
    { method: "Contains()", complexity: "O(1)", notes: "Amortized" },
    { method: "Remove()", complexity: "O(1)", notes: "Amortized" },
    { method: "UnionWith()", complexity: "O(n)", notes: "" },
    { method: "IntersectWith()", complexity: "O(n)", notes: "" },
    { method: "Count", complexity: "O(1)", notes: "Property" },
    { method: "Clear()", complexity: "O(n)", notes: "" },
  ],
  sorteddict: [
    { method: "Add()", complexity: "O(log n)", notes: "Red-black tree" },
    { method: "dict[key]", complexity: "O(log n)", notes: "" },
    { method: "Remove()", complexity: "O(log n)", notes: "" },
    { method: "ContainsKey()", complexity: "O(log n)", notes: "" },
    { method: "Count", complexity: "O(1)", notes: "Property" },
  ],
  string: [
    { method: "str[i]", complexity: "O(1)", notes: "" },
    { method: "IndexOf()", complexity: "O(n)", notes: "" },
    { method: "Substring()", complexity: "O(n)", notes: "" },
    { method: "Contains()", complexity: "O(n)", notes: "" },
    { method: "Replace()", complexity: "O(n)", notes: "" },
    { method: "Split()", complexity: "O(n)", notes: "" },
    { method: "ToLower()", complexity: "O(n)", notes: "" },
    { method: "Trim()", complexity: "O(n)", notes: "" },
    { method: "Length", complexity: "O(1)", notes: "Property" },
    { method: "Equals()", complexity: "O(n)", notes: "" },
    { method: "StartsWith()", complexity: "O(n)", notes: "" },
  ],
};

export const DATA_OF_ALL_LANG_COMPLEXITY: Record<string, LangData> = {
  cpp: CPP_TIME_COMPL,
  rust: RUST_TIME_COMPL,
  nodejs: NODEJS_TIME_COMPL,
  python: PYTHON_TIME_COMPL,
  c: C_TIME_COMPL,
  java: JAVA_TIME_COMPL,
  csharp: CSHARP_TIME_COMPL,
};
